name: CI
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read
jobs:
  test:
    name: Julia ${{ matrix.version }}-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.XPRESS_JLL_VERSION }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ['1.6', '1']  # Test against LTS and current minor release
        os: [ubuntu-latest, macOS-latest, windows-latest]
        arch: [x64]
        XPRESS_JLL_VERSION: ['8.13.4', '9.3.0']
        include:
         - version: '1'
           os: macos-14
           arch: aarch64
           XPRESS_JLL_VERSION: '9.3.0'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
        env:
          XPRESS_JL_SKIP_LIB_CHECK: "true"
      - shell: julia --project=. --color=yes {0}
        run: |
          import Pkg
          Pkg.add("Xpress_jll")
          import Xpress_jll
          # Assume Pkg has installed the latest version with a valid community
          # license. Copy it to the current directory.
          write(
              "xpauth.xpr",
              joinpath(dirname(dirname(Xpress_jll.libxprs)), "license", "community-xpauth.xpr"),
          )
          # Now install the specific version of Xpress
          Pkg.add(; name = "Xpress_jll", version = ENV["XPRESS_JLL_VERSION"])
        env:
          XPRESS_JLL_VERSION: ${{ matrix.XPRESS_JLL_VERSION }}
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
